name: github-actions
on: [push]
jobs:
  install-build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g yarn
    - run: yarn
    - run: yarn build
    - run: yarn synth
#    - name: AWS CDK Deploy
#      uses:
#      with:
#       args: deploy --require-approval never
#      env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_REGION: us-east-1
