name: github-actions
on: [push]
jobs:
  install-build:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g yarn
    - run: yarn
    - run: yarn build
    - run: yarn synth
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@master
      env:
       DISTRIBUTION: ${{ secrets.DISTRIBUTION_ONE }}
       PATHS: '/index.html'
       AWS_REGION: 'us-east-1'
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: invalidate2
      uses: chetan/invalidate-cloudfront-action@master
      env:
       DISTRIBUTION: ${{ secrets.DISTRIBUTION_TWO }}
       PATHS: '/index.html'
       AWS_REGION: 'us-east-1'
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - run: yarn deploy
