name: github-actions
on: [push]
jobs:
  install-build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@latest
    - run: yarn install
    - run: yarn build
