name: github-actions
on: [push]
jobs:
  install-build:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
    - run: yarn install
    - run: yarn build
